all: bin/EVALB/evalb cython

cython:
	python setup.py build_ext -i

install: cython
	pip install -e .

clean: cython-clean
	find -name '*.so' | xargs rm -rf
	rm -rf build
	rm -rf ldp.egg-info
	rm -rf .coverage coverage-report
	find -name '*.pyc' -exec rm {} \;
	find -name '*.so' -exec rm {} \;
	find -name '*.html' -exec rm {} \;

notebook:
	ipython notebook notebooks

pylint:
	pylint --disable=W0142,W0232,W0212,W0614,W0611,C,R ldp

bin/EVALB/evalb:
	(cd bin/EVALB && make )

tests: all
	./bin/test

cython-clean:
	(cd ldp ; find . -name '*.cpp'  -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd ldp ; find . -name '*.c'    -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd ldp ; find . -name '*.html' -print0 |xargs -0 ack --print0 --files-with-matches 'Generated by Cython'     |xargs -0 rm -f)
